### ISSUE TITLE
[Bug] Parsing files in the same directory (i.e. without `./`) doesn't work

### ISSUE THREAD

**Issue by philwinder** [ipld/go-ipldtool#12]
Following [this example](https://github.com/ipld/go-ipldtool/blob/master/docs/schema.md).

I ran `ipld schema parse test.ipldsch` instead of `ipld schema parse ./test.ipldsch` and was surprised with a panic. Following the code I [found this](https://github.com/ipld/go-ipldtool/blob/master/app/shared/args.go#L21). There's probably a better way to test if a file exists.

**Comment by rvagg** [comment]
I guess this is trying to leave open the possibility of supplying a CID.
I reckon the safest thing to do for now is just test for file existence and use that, if it's not `-` then that should be reasonable. Smarts can be added later, including CID parsing.
Would you like to contribute a fix for this @philwinder? `os.Stat(x)` should error if the file doesn't exist. And `errors.Is(err, os.ErrNotExist)` can be used to tell if it's because it doesn't exist or there was some other error. Alternatively just naively go ahead and read it if it's not `"-"` and read the file and use the error output of that when it doesn't exist.
